server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
        target_label: service
      - source_labels: ['__meta_docker_container_label_env']
        target_label: env
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: container_name
      - source_labels: ['__meta_docker_container_id']
        target_label: container_id
    pipeline_stages:
      - docker: {}
      # Parse JSON application logs (morgan + winston) when present.
      # Keep labels low-cardinality to avoid Loki index blowup.
      - json:
          expressions:
            level: level
            req_id: req_id
            type: type
            status: status
            path: path
            rt_ms: rt_ms
      - labels:
          level:
          type:
