server:
  http_listen_port: 3200
  log_level: info

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
        http:

ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
  trace_idle_period: 10s
  max_block_bytes: 1048576
  max_block_duration: 5m

storage:
  trace:
    backend: local
    wal:
      path: /var/lib/tempo/wal
    local:
      path: /var/lib/tempo/blocks

querier: {}
query_frontend: {}
compactor:
  shared_store: filesystem
  working_directory: /var/lib/tempo/compactor
  compaction:
    compaction_window: 1h
    max_block_bytes: 100000000
    block_retention: 168h
    compacted_block_retention: 10m
