server:
  http_listen_port: 3200

distributor:
  receivers:
    otlp:
      protocols:
        grpc:

ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
  trace_idle_period: 10s
  max_block_bytes: 1048576
  max_block_duration: 5m

storage:
  trace:
    backend: local
    wal:
      path: /tmp/tempo/wal
    local:
      path: /tmp/tempo/blocks

querier: {}
query_frontend: {}
compactor:
  compaction:
    compaction_window: 1h
    max_block_bytes: 100000000
    block_retention: 48h
    compacted_block_retention: 10m

