export const ERROR_MESSAGES = {
  unauthorized: 'Требуется авторизация',
  internal_error: 'Произошла ошибка сервера. Попробуйте позже.',
  account_locked: 'Аккаунт заблокирован',
  already_confirmed: 'Электронная почта уже подтверждена',
  bank_account_exists: 'Банковский счёт уже указан',
  bank_account_invalid: 'Неверные реквизиты счёта',
  bank_account_locked: 'Банковский счёт заблокирован',
  bank_account_not_found: 'Банковский счёт не найден',
  bank_not_found: 'Банк не найден',
  sign_type_simple_required:
    'Требуется простая электронная подпись. Настройте её в разделе «Документы»',
  country_not_found: 'Страна не найдена',
  document_type_not_found: 'Тип документа не найден',
  email_exists: 'Email уже зарегистрирован',
  inn_exists: 'ИНН уже зарегистрирован',
  inn_not_found: 'ИНН не найден',
  invalid_code: 'Неверный код',
  invalid_credentials: 'Неверные учётные данные',
  invalid_passport: 'Неверные данные паспорта',
  invalid_token: 'Некорректный или истёкший токен',
  invalid_token_type: 'Некорректный тип токена',
  invalid_type_id: 'Некорректный тип нормативного упражнения',
  invalid_value: 'Некорректное значение',
  weak_password:
    'Пароль слишком простой. Минимум 8 символов, латинские буквы и цифры. Рекомендуем добавить заглавные буквы и спецсимволы.',
  invalid_email: 'Неверный формат email',
  invalid_phone: 'Неверный номер телефона',
  sex_required: 'Укажите пол',
  invalid_birth_date: 'Введите корректную дату рождения',
  missing_token: 'Отсутствует токен авторизации',
  passport_exists: 'Паспорт уже добавлен',
  passport_not_found: 'Паспорт не найден',
  phone_exists: 'Телефон уже зарегистрирован',
  role_not_found: 'Роль не найдена',
  snils_exists: 'СНИЛС уже зарегистрирован',
  snils_not_found: 'СНИЛС не найден',
  status_not_found: 'Статус не найден',
  status_required: 'Не указан статус',
  taxation_not_found: 'Налоговый статус не найден',
  certificate_not_found: 'Медицинское заключение не найдено',
  ground_not_found: 'Площадка не найдена',
  equipment_not_found: 'Экипировка не найдена',
  equipment_already_assigned: 'Экипировка уже выдана другому получателю',
  equipment_assignment_exists:
    'Уже оформлен акт выдачи для этой единицы. Дождитесь подписи или отмените выдачу.',
  training_not_found: 'Тренировка не найдена',
  registration_not_found: 'Запись не найдена',
  registration_closed: 'Запись закрыта',
  cancellation_deadline_passed:
    'Нельзя отменить запись менее чем за 48 часов до начала',
  cancellation_forbidden: 'Отменять запись могут только участники',
  already_registered: 'Уже зарегистрированы',
  referee_group_not_found: 'Группа судей не найдена',
  access_denied: 'Доступ запрещен',
  invalid_address: 'Некорректный адрес',
  user_exists: 'Пользователь уже существует',
  user_not_found: 'Пользователь не найден',
  player_not_found: 'Игрок не найден',
  player_id_required: 'Не указан игрок',
  file_required: 'Не выбрано изображение',
  photo_request_forbidden:
    'Недостаточно прав для загрузки фотографии этого игрока',
  photo_request_not_found: 'Заявка не найдена',
  photo_request_already_processed: 'Заявка уже обработана',
  photo_request_already_exists: 'Заявка уже отправлена и ожидает проверки',
  photo_request_status_missing:
    'Конфигурация статусов заявок недоступна. Обратитесь в поддержку.',
  photo_request_status_invalid: 'Некорректный статус заявки',
  file_too_large: 'Файл слишком большой',
  image_too_small: 'Разрешение слишком низкое. Минимум 800×800 пикселей',
  invalid_file_type: 'Недопустимый формат файла',
  agreement_not_found: 'Протокол не найден',
  agreement_already_signed: 'Протокол уже подписан',
  agreement_signature_missing: 'Необходимо подписать документ',
  match_not_found: 'Матч не найден',
  match_locked: 'Матч закрыт для изменений',
  match_lineup_locked: 'Заявка на матч заблокирована',
  match_lineup_not_found: 'Заявка не найдена',
  match_lineup_player_exists: 'Игрок уже присутствует в заявке',
  match_lineup_staff_exists: 'Представитель уже присутствует в заявке',
  match_lineup_conflict: 'Состав был изменён другим пользователем',
  team_not_found: 'Команда не найдена',
  team_locked: 'Команда заблокирована для изменений',
  team_player_not_found: 'Игрок команды не найден',
  team_staff_not_found: 'Представитель команды не найден',
  lineup_export_forbidden: 'Недостаточно прав для экспорта состава',
  lineup_export_failed: 'Не удалось подготовить выгрузку состава',
  player_ids_must_be_array: 'Некорректный формат списка игроков',
  player_ids_must_be_array_of_strings: 'Некорректные идентификаторы игроков',
  forbidden_not_team_member:
    'Недостаточно прав для редактирования состава команды',
  too_many_goalkeepers: 'В составе на матч не может быть более двух вратарей',
  too_many_field_players: 'Нельзя выбрать более 20 полевых игроков',
  too_few_goalkeepers: 'Минимум 1 вратарь в заявке',
  too_few_field_players: 'Минимум 5 полевых игроков в заявке',
  squad_number_required:
    'Для каждого выбранного игрока укажите состав (1 или 2)',
  too_few_or_many_goalkeepers:
    'В каждом составе должно быть от 1 до 2 вратарей',
  invalid_field_players_for_double:
    'В каждом составе должно быть от 12 до 13 полевых игроков',
  too_many_players_in_squad: 'В каждом составе нельзя выбрать более 15 игроков',
  too_many_goalkeepers_both:
    'Можно указать только одного вратаря для обоих составов',
  too_few_coaches: 'Минимум 2 тренера в заявке',
  too_many_officials: 'Нельзя выбрать более 8 официальных представителей',
  head_coach_required: 'Необходимо назначить главного тренера команды',
  too_many_coaches_per_squad:
    'В каждом составе нельзя выбрать более 4 тренеров',
  gk_both_requires_three:
    'Для отметки «Оба состава» необходимо выбрать минимум трёх вратарей',
  captain_required: 'Необходимо указать капитана команды',
  too_many_captains: 'Можно выбрать только одного капитана',
  too_many_assistants: 'Можно выбрать не более двух ассистентов капитана',
  captain_must_be_field_player: 'Капитаном может быть только полевой игрок',
  assistant_must_be_field_player: 'Ассистентом может быть только полевой игрок',
  captain_cannot_be_assistant: 'Капитан не может быть ассистентом одновременно',
  too_many_head_coaches: 'Можно выбрать только одного главного тренера',
  staff_role_required: 'Выберите должность для всех выбранных представителей',
  staff_ids_must_be_array: 'Некорректный формат списка представителей',
  staff_ids_must_be_array_of_strings:
    'Некорректные идентификаторы представителей',
  staff_not_in_team: 'Некорректный представитель команды',
  match_role_required: 'Выберите амплуа для всех выбранных игроков',
  match_number_required: 'Укажите номер для всех выбранных игроков',
  grip_required: 'Выберите хват',
  invalid_grip: 'Некорректный хват',
  invalid_height: 'Рост должен быть от 90 до 220 см',
  invalid_weight: 'Вес должен быть от 10 до 140 кг',
  jersey_required: 'Укажите номер игрока',
  jersey_invalid: 'Номер должен быть от 1 до 99',
  role_required: 'Выберите амплуа',
  duplicate_match_numbers: 'Игровые номера в матче должны быть уникальными',
  conflict_lineup_version:
    'Состав был изменён с другого устройства. Обновили данные. Повторяем сохранение…',
  conflict_staff_version:
    'Список представителей был изменён с другого устройства. Обновили данные. Повторяем сохранение…',
  validation_error: 'Проверьте корректность введённых данных',
  rate_limited:
    'Слишком много запросов. Пожалуйста, подождите и попробуйте снова.',
} as const;

export type ErrorCode = keyof typeof ERROR_MESSAGES;

export function translateError(code: string | null | undefined): string {
  if (!code) return '';
  const normalized = code.trim();
  if (!normalized) return '';
  const key = normalized as ErrorCode;
  return ERROR_MESSAGES[key] ?? 'Ошибка запроса';
}
