export const ERROR_MESSAGES = {
  account_locked: 'Аккаунт заблокирован',
  already_confirmed: 'Электронная почта уже подтверждена',
  bank_account_exists: 'Банковский счёт уже указан',
  bank_account_invalid: 'Неверные реквизиты счёта',
  bank_account_locked: 'Банковский счёт заблокирован',
  bank_account_not_found: 'Банковский счёт не найден',
  bank_not_found: 'Банк не найден',
  country_not_found: 'Страна не найдена',
  document_type_not_found: 'Тип документа не найден',
  email_exists: 'Email уже зарегистрирован',
  inn_exists: 'ИНН уже зарегистрирован',
  inn_not_found: 'ИНН не найден',
  invalid_code: 'Неверный код',
  invalid_credentials: 'Неверные учётные данные',
  invalid_passport: 'Неверные данные паспорта',
  invalid_token: 'Некорректный или истёкший токен',
  invalid_token_type: 'Некорректный тип токена',
  invalid_type_id: 'Некорректный тип нормативного упражнения',
  invalid_value: 'Некорректное значение',
  missing_token: 'Отсутствует токен авторизации',
  passport_exists: 'Паспорт уже добавлен',
  passport_not_found: 'Паспорт не найден',
  phone_exists: 'Телефон уже зарегистрирован',
  role_not_found: 'Роль не найдена',
  snils_exists: 'СНИЛС уже зарегистрирован',
  snils_not_found: 'СНИЛС не найден',
  status_not_found: 'Статус не найден',
  status_required: 'Не указан статус',
  taxation_not_found: 'Налоговый статус не найден',
  certificate_not_found: 'Медицинское заключение не найдено',
  ground_not_found: 'Площадка не найдена',
  training_not_found: 'Тренировка не найдена',
  registration_not_found: 'Запись не найдена',
  registration_closed: 'Запись закрыта',
  cancellation_deadline_passed:
    'Нельзя отменить запись менее чем за 48 часов до начала',
  cancellation_forbidden: 'Отменять запись могут только участники',
  already_registered: 'Уже зарегистрированы',
  referee_group_not_found: 'Группа судей не найдена',
  access_denied: 'Доступ запрещен',
  invalid_address: 'Некорректный адрес',
  user_exists: 'Пользователь уже существует',
  user_not_found: 'Пользователь не найден',
  file_too_large: 'Файл слишком большой',
  invalid_file_type: 'Недопустимый тип файла',
  accepted_required: 'Необходимо согласие с правилами',
  address_not_found: 'Адрес не найден',
  awaiting_confirmation: 'Ожидается подтверждение',
  email_unconfirmed: 'Электронная почта не подтверждена',
  file_required: 'Не выбран файл',
  active_ticket_exists: 'Есть активное обращение данного типа',
  registration_incomplete: 'Регистрация не завершена',
  status_unknown: 'Неизвестный статус',
  not_found: 'Не найдено',
};

export function translateError(code) {
  if (!code) return '';
  return ERROR_MESSAGES[code] || code;
}
