stages:
  - test

variables:
  NODE_ENV: test

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - client/node_modules/

test:node
  stage: test
  image: node:24
  before_script:
    - node -v && npm -v
    - npm ci
  script:
    - npm run lint
    - npm run format:check
    - npm run validate:dashboards
    - npm test -- --runInBand
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
  artifacts:
    when: always
    reports:
      junit: junit.xml
    expire_in: 1 week

