services:
  app:
    logging:
      driver: loki
      options:
        loki-url: "http://host.docker.internal:3100/loki/api/v1/push"
        labels: "service,env,container_name"
        env: "NODE_ENV,VERSION"
    labels:
      service: "api"
      env: "dev"

  client:
    logging:
      driver: loki
      options:
        loki-url: "http://host.docker.internal:3100/loki/api/v1/push"
        labels: "service,env,container_name"
        env: "NODE_ENV,VERSION"
    labels:
      service: "client"
      env: "dev"

# Note: This override expects the Loki Docker logging plugin to be installed:
#   docker plugin install grafana/loki-docker-driver:latest --alias loki --grant-all-permissions
# On Linux, replace host.docker.internal with the host IP if not available.

