services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    platform: ${DOCKER_PLATFORM:-linux/amd64}
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    platform: ${DOCKER_PLATFORM:-linux/amd64}
    depends_on:
      - app
    ports:
      - "5173:4173"
    networks:
      - backend

  db:
    image: postgres:17
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USER}", "-d", "${DB_NAME}"]
      interval: 5s
      retries: 5
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend
    restart: unless-stopped

volumes:
  db-data:

networks:
  backend:
    driver: bridge
