import { DataTypes, Model } from 'sequelize';

import sequelize from '../config/database.js';

class Address extends Model {}

Address.init(
  {
    id: {
      type: DataTypes.UUID,
      defaultValue: DataTypes.UUIDV4,
      primaryKey: true,
    },
    source: { type: DataTypes.STRING(250) },
    result: { type: DataTypes.STRING(500) },
    postal_code: { type: DataTypes.STRING(10) },
    country: { type: DataTypes.STRING(150) },
    country_iso_code: { type: DataTypes.STRING(10) },
    federal_district: { type: DataTypes.STRING(20) },
    region_fias_id: { type: DataTypes.STRING(50) },
    region_kladr_id: { type: DataTypes.STRING(20) },
    region_iso_code: { type: DataTypes.STRING(10) },
    region_with_type: { type: DataTypes.STRING(150) },
    region_type: { type: DataTypes.STRING(10) },
    region_type_full: { type: DataTypes.STRING(50) },
    region: { type: DataTypes.STRING(150) },
    area_fias_id: { type: DataTypes.STRING(50) },
    area_kladr_id: { type: DataTypes.STRING(20) },
    area_with_type: { type: DataTypes.STRING(150) },
    area_type: { type: DataTypes.STRING(10) },
    area_type_full: { type: DataTypes.STRING(50) },
    area: { type: DataTypes.STRING(150) },
    city_fias_id: { type: DataTypes.STRING(50) },
    city_kladr_id: { type: DataTypes.STRING(20) },
    city_with_type: { type: DataTypes.STRING(150) },
    city_type: { type: DataTypes.STRING(10) },
    city_type_full: { type: DataTypes.STRING(50) },
    city: { type: DataTypes.STRING(150) },
    city_area: { type: DataTypes.STRING(150) },
    city_district_fias_id: { type: DataTypes.STRING(50) },
    city_district_kladr_id: { type: DataTypes.STRING(20) },
    city_district_with_type: { type: DataTypes.STRING(150) },
    city_district_type: { type: DataTypes.STRING(10) },
    city_district_type_full: { type: DataTypes.STRING(50) },
    city_district: { type: DataTypes.STRING(150) },
    settlement_fias_id: { type: DataTypes.STRING(50) },
    settlement_kladr_id: { type: DataTypes.STRING(20) },
    settlement_with_type: { type: DataTypes.STRING(150) },
    settlement_type: { type: DataTypes.STRING(10) },
    settlement_type_full: { type: DataTypes.STRING(50) },
    settlement: { type: DataTypes.STRING(150) },
    street_fias_id: { type: DataTypes.STRING(50) },
    street_kladr_id: { type: DataTypes.STRING(20) },
    street_with_type: { type: DataTypes.STRING(150) },
    street_type: { type: DataTypes.STRING(10) },
    street_type_full: { type: DataTypes.STRING(50) },
    street: { type: DataTypes.STRING(150) },
    stead_fias_id: { type: DataTypes.STRING(50) },
    stead_kladr_id: { type: DataTypes.STRING(20) },
    stead_cadnum: { type: DataTypes.STRING(50) },
    stead_type: { type: DataTypes.STRING(10) },
    stead_type_full: { type: DataTypes.STRING(50) },
    stead: { type: DataTypes.STRING(50) },
    house_fias_id: { type: DataTypes.STRING(50) },
    house_kladr_id: { type: DataTypes.STRING(20) },
    house_cadnum: { type: DataTypes.STRING(50) },
    house_type: { type: DataTypes.STRING(10) },
    house_type_full: { type: DataTypes.STRING(50) },
    house: { type: DataTypes.STRING(50) },
    house_flat_count: { type: DataTypes.STRING(10) },
    block_type: { type: DataTypes.STRING(10) },
    block_type_full: { type: DataTypes.STRING(50) },
    block: { type: DataTypes.STRING(50) },
    entrance: { type: DataTypes.STRING(10) },
    floor: { type: DataTypes.STRING(10) },
    flat_fias_id: { type: DataTypes.STRING(50) },
    flat_cadnum: { type: DataTypes.STRING(50) },
    flat_type: { type: DataTypes.STRING(10) },
    flat_type_full: { type: DataTypes.STRING(50) },
    flat: { type: DataTypes.STRING(50) },
    flat_area: { type: DataTypes.STRING(50) },
    square_meter_price: { type: DataTypes.STRING(50) },
    flat_price: { type: DataTypes.STRING(50) },
    postal_box: { type: DataTypes.STRING(50) },
    room_type: { type: DataTypes.STRING(10) },
    room_type_full: { type: DataTypes.STRING(50) },
    room: { type: DataTypes.STRING(50) },
    fias_id: { type: DataTypes.STRING(50) },
    fias_code: { type: DataTypes.STRING(50) },
    fias_level: { type: DataTypes.STRING(10) },
    fias_actuality_state: { type: DataTypes.STRING(10) },
    kladr_id: { type: DataTypes.STRING(20) },
    geoname_id: { type: DataTypes.STRING(20) },
    capital_marker: { type: DataTypes.STRING(10) },
    okato: { type: DataTypes.STRING(20) },
    oktmo: { type: DataTypes.STRING(20) },
    tax_office: { type: DataTypes.STRING(10) },
    tax_office_legal: { type: DataTypes.STRING(10) },
    timezone: { type: DataTypes.STRING(50) },
    geo_lat: { type: DataTypes.STRING(20) },
    geo_lon: { type: DataTypes.STRING(20) },
    beltway_hit: { type: DataTypes.STRING(10) },
    beltway_distance: { type: DataTypes.STRING(10) },
    qc_geo: { type: DataTypes.INTEGER },
    qc_complete: { type: DataTypes.INTEGER },
    qc_house: { type: DataTypes.INTEGER },
    qc: { type: DataTypes.INTEGER },
    unparsed_parts: { type: DataTypes.STRING(250) },
    metro: { type: DataTypes.JSONB },
    divisions: { type: DataTypes.JSONB },
  },
  {
    sequelize,
    modelName: 'Address',
    tableName: 'addresses',
    paranoid: true,
    underscored: true,
  }
);

export default Address;
